[package]
name = "uranium-tabs"
version = "0.1.0"
edition = "2021"

[lib]
name = "uranium_tabs"
path = "src/lib.rs"

[[bin]]
name = "uranium-tabs"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
