#!/bin/sh
# Unpack a pm dependency closure into a usable sysroot.
#
# pm carries dependencies without consuming them. A dependency's archive is
# copied to /dest/deps/<name>-<version>.cpkg and NOTHING unpacks it: there is no
# store, no prefix, and nothing sets -I, -L or PKG_CONFIG_PATH. Only DIRECT
# dependencies appear in deps/ -- the tree is carried nested, not flattened, so
# each .cpkg contains its own deps/ with its own dependencies inside it.
#
# So this walks that nesting and flattens it. It is the single piece of glue
# that makes a multi-package build possible at all in pm today, and it lives in
# this repository rather than in pm because it is a workaround, not a feature.
#
# It is a shell script for a reason that is not laziness: a build step has no
# shell, so a loop over an unknown number of archives cannot be expressed as
# pm `run:` commands. Invoked as two plain words -- `/bin/sh <abs>/sysroot.sh`
# -- it matches pm's `shell` fingerprint, which is the sanctioned escape hatch
# (see the "There is no shell" section of pm's examples/README.md).
#
# Usage: sh sysroot.sh <deps-dir> <sysroot-dir>

set -eu

DEPS="${1:?usage: sysroot.sh <deps-dir> <sysroot-dir>}"
ROOT="${2:?usage: sysroot.sh <deps-dir> <sysroot-dir>}"

mkdir -p "$ROOT"

# A package with no dependencies still calls this, so an absent deps/ is normal
# and not an error. Exiting 0 here keeps every recipe's Prepare stage uniform.
if [ ! -d "$DEPS" ]; then
  echo "sysroot: no deps directory at $DEPS; nothing to unpack"
  exit 0
fi

# Breadth-first over the nesting. `pending` is a directory of .cpkg files to
# unpack; unpacking one may reveal a deps/ of its own, which becomes the next
# round. A plain recursive function would be fine too, but this keeps the
# extraction scratch space in one place and makes the trace readable.
scratch="${TMPDIR:-/tmp}/sysroot.$$"
mkdir -p "$scratch"
round=0
pending="$DEPS"

while [ -n "$pending" ] && [ -d "$pending" ]; do
  round=$((round + 1))
  next="$scratch/round-$round-deps"
  mkdir -p "$next"
  found=0

  for archive in "$pending"/*.cpkg; do
    # An unmatched glob stays literal in POSIX sh; skip it rather than trying
    # to untar a path that does not exist.
    [ -e "$archive" ] || continue
    found=1
    name=$(echo "$archive" | sed 's|.*/||; s|\.cpkg$||')
    stage="$scratch/$name"
    mkdir -p "$stage"
    echo "sysroot: unpacking $name"
    tar -xpf "$archive" -C "$stage"

    # The payload. `metadata` is pm's own member at the archive root and has no
    # business in a sysroot, so it is left behind with the rest of the staging
    # directory.
    if [ -d "$stage/usr" ]; then
      tar -cf - -C "$stage" usr | tar -xpf - -C "$ROOT"
    fi
    # This package's own dependencies, queued for the next round.
    if [ -d "$stage/deps" ]; then
      cp -a "$stage/deps/." "$next/" 2>/dev/null || true
    fi
  done

  [ "$found" -eq 1 ] || break
  pending="$next"
done

# Rewrite pkg-config prefixes.
#
# This is the decision that makes the sysroot work with meson, cmake and
# autotools alike, with no per-build-system special case and no `env` wrapper.
# Every .pc file staged above was generated by a build that was told
# --prefix=/usr, so it claims prefix=/usr -- but the files are actually under
# $ROOT/usr. A consumer reading it would be handed -I/usr/include, silently
# find the HOST's headers in pm's read-only /usr mirror, and compile against
# the wrong library version without a single warning.
#
# The alternative was PKG_CONFIG_SYSROOT_DIR, which would need an `env` wrapper
# on every configure command -- and `env` defeats pm's fingerprint check,
# because the pattern is anchored at the program name and matches the first
# word only. Rewriting the files keeps that check meaningful. See
# docs/pm-constraints.md.
for dir in "$ROOT/usr/lib/pkgconfig" "$ROOT/usr/share/pkgconfig" \
           "$ROOT/usr/lib64/pkgconfig"; do
  [ -d "$dir" ] || continue
  find "$dir" -name '*.pc' -exec \
    sed -i "s|^prefix=/usr\$|prefix=$ROOT/usr|" {} +
done

rm -rf "$scratch"
echo "sysroot: ready at $ROOT"
